"""
train_pd_model.py — Trains the synthetic Probability-of-Default (PD) model.

Run this ONCE before using the agent:
    python -m src.tools.train_pd_model

It generates synthetic borrower data, trains a logistic regression classifier,
and saves the model to models/pd_model.pkl.

WHY A REAL MODEL INSTEAD OF JUST PROMPTING THE LLM?

In real banking, PD models are subject to SR 11-7 model risk management.
That means:
- They must be explainable (logistic regression coefficients are visible).
- They must be reproducible (same inputs → same outputs, every time).
- They must be backtestable (you can test them against historical defaults).

LLM prompting cannot meet any of these requirements. So even though our model
is trained on synthetic data and isn't "real", the architectural separation
(real ML model + LLM narration) is exactly what production banks do.

"""

import os
import pickle
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, classification_report


MODEL_DIR = "models"
MODEL_PATH = os.path.join(MODEL_DIR, "pd_model.pkl")


def generate_synthetic_borrowers(n: int = 5000, random_seed: int = 42) -> pd.DataFrame:
    """
    Generate synthetic borrower data for training.
    
    The "default" outcome is generated by a known underlying rule, so the
    model can learn it. In real life, you'd train on actual default data
    accumulated over years.
    
    Features generated:
    - leverage_ratio
    - interest_coverage
    - current_ratio
    - debt_to_equity
    - ebitda_margin
    
    Default rate ~12-15% (realistic for a wholesale loan portfolio).
    """
    rng = np.random.default_rng(random_seed)
    
    # Generate features with realistic distributions
    leverage = np.clip(rng.lognormal(mean=1.0, sigma=0.6, size=n), 0.1, 15.0)
    coverage = np.clip(rng.lognormal(mean=1.5, sigma=0.7, size=n), 0.1, 30.0)
    current = np.clip(rng.lognormal(mean=0.3, sigma=0.4, size=n), 0.2, 5.0)
    de = np.clip(rng.lognormal(mean=0.0, sigma=0.6, size=n), 0.1, 6.0)
    margin = np.clip(rng.normal(loc=0.15, scale=0.08, size=n), -0.10, 0.45)
    
    # Compute "true" default probability using a logistic function with known coefficients
    # Higher leverage → higher PD; higher coverage/margin/liquidity → lower PD
    z = (
        -3.5                      # base: low default rate for healthy firms
        + 0.45 * leverage         # +0.45 per unit of leverage
        - 0.30 * coverage         # better coverage lowers default risk
        - 0.50 * current          # better liquidity lowers default risk
        + 0.20 * de               # higher debt/equity raises risk
        - 4.0 * margin            # higher margin lowers risk strongly
    )
    
    true_pd = 1.0 / (1.0 + np.exp(-z))  # logistic
    defaulted = rng.binomial(1, true_pd)  # actual outcomes
    
    df = pd.DataFrame({
        "leverage_ratio": leverage,
        "interest_coverage": coverage,
        "current_ratio": current,
        "debt_to_equity": de,
        "ebitda_margin": margin,
        "defaulted": defaulted,
    })
    
    return df


def train_and_save() -> None:
    """Generate data, train model, evaluate, save to disk."""
    print("Generating synthetic training data (5,000 borrowers)...")
    df = generate_synthetic_borrowers(n=5000)
    
    print(f"  Default rate in training data: {df['defaulted'].mean():.1%}")
    
    # Split features and target
    X = df[["leverage_ratio", "interest_coverage", "current_ratio", "debt_to_equity", "ebitda_margin"]]
    y = df["defaulted"]
    
    # Train/test split for evaluation
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    
    # Pipeline: standardize features, then logistic regression
    # Why standardize? Logistic regression's coefficients are easier to interpret 
    # when features are on the same scale.
    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(max_iter=1000, random_state=42)),
    ])
    
    print("Training logistic regression...")
    pipeline.fit(X_train, y_train)
    
    # Evaluate
    y_pred = pipeline.predict(X_test)
    y_proba = pipeline.predict_proba(X_test)[:, 1]
    auc = roc_auc_score(y_test, y_proba)
    
    print(f"\nModel Performance on Held-Out Test Set:")
    print(f"  AUC-ROC: {auc:.3f}  (>0.7 is decent for credit; >0.8 is strong)")
    print(f"\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=["non-default", "default"]))
    
    # Save the model
    os.makedirs(MODEL_DIR, exist_ok=True)
    with open(MODEL_PATH, "wb") as f:
        pickle.dump(pipeline, f)
    
    print(f"\nModel saved to {MODEL_PATH}")
    print("You can now run the agent.")


if __name__ == "__main__":
    train_and_save()
